id: P004352
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:14:01.590439
source_metadata:
  id: bdr:W8LS19189
  title: རྒྱུད་བཞིའི་འགྲེལ་བ་མེས་པོའི་ཞལ་ལུང་། སྟོད་ཆ།
  author: ''
  volumes:
    267ad7fdab1246a7b14eb2c06e27366b:
      image_group_id: I8LS19191
      title: ''
      volume_number: 1
      total_pages: 1022
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
