id: ID8B13166
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:48:40+00:00'
last_modified: '2022-06-07T22:13:28.101240+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19189
  title: རྒྱུད་བཞིའི་འགྲེལ་བ་མེས་པོའི་ཞལ་ལུང་། སྟོད་ཆ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E66B:
      image_group_id: I8LS19191
      title: ''
      total_pages: 1022
      order: 1
      base_file: E66B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
